ci:
  collect:
    settings:
      configPath: "./config/lr-desktop-config.js"
    numberOfRuns: 5
    startServerCommand: npm run build
    url:
      - https://www.elcolombiano.com/
      - https://www.elcolombiano.com/inicio-sesion
  assert:
    preset: lighthouse:recommended
    assertions:
      categories:performance:['warn',{minScore: 0.6}],
  upload:
    target: temporary-public-storage
    # serverBaseUrl: https://lhci.example.com
